# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /media/sf_verilog-projects/lab2-2B/lab2-2B.cache/wt [current_project]
set_property parent.project_path /media/sf_verilog-projects/lab2-2B/lab2-2B.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  /media/sf_verilog-projects/lab2-2B/lab2-2B.srcs/sources_1/imports/sf_verilog-projects/clkdiv.v
  /media/sf_verilog-projects/lab2-2B/lab2-2B.srcs/sources_1/new/serdetect.v
  /media/sf_verilog-projects/lab2-2B/lab2-2B.srcs/sources_1/new/serdetect_disp.v
}
read_xdc /media/sf_verilog-projects/lab2-2B/lab2-2B.srcs/constrs_1/imports/sf_verilog-projects/Nexys4_Master.xdc
set_property used_in_implementation false [get_files /media/sf_verilog-projects/lab2-2B/lab2-2B.srcs/constrs_1/imports/sf_verilog-projects/Nexys4_Master.xdc]

synth_design -top serdetect_disp -part xc7a100tcsg324-1
write_checkpoint -noxdef serdetect_disp.dcp
catch { report_utilization -file serdetect_disp_utilization_synth.rpt -pb serdetect_disp_utilization_synth.pb }
