# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/verilog/QUESTD/QUESTD.cache/wt [current_project]
set_property parent.project_path D:/verilog/QUESTD/QUESTD.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  D:/verilog/QUESTD/QUESTD.srcs/sources_1/imports/verilog/clkdiv.v
  D:/verilog/QUESTD/QUESTD.srcs/sources_1/imports/new/shftreg3.v
  D:/verilog/QUESTD/QUESTD.srcs/sources_1/new/combination.v
}
read_xdc D:/verilog/QUESTD/QUESTD.srcs/constrs_1/imports/verilog/quest2.xdc
set_property used_in_implementation false [get_files D:/verilog/QUESTD/QUESTD.srcs/constrs_1/imports/verilog/quest2.xdc]

synth_design -top combination -part xc7a100tcsg324-1
write_checkpoint -noxdef combination.dcp
catch { report_utilization -file combination_utilization_synth.rpt -pb combination_utilization_synth.pb }
